[package]
name = "algo_test_bed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand_seeder = "0.2"
rand = "0.8"
rand_pcg = "0.3"
chrono = "0.4"
getrandom = { version = "0.2", features = ["js"] }